#!/usr/bin/env python3
"""Build MIMZY — the single quantum workbench, assembled ONLY from the instruments that
passed the shelf audit (real physics, real quantum theory, simulations verified).
Conceit (silicon layer, labeled): futuristic tech that comes from the past — the
Antikythera mechanism, Ada's Notes, Babbage's unbuilt engine, Turing's classified work,
and the other things lost in the cracks. After 'Mimsy Were the Borogoves' (1943) and
The Last Mimzy (2007) — fan tribute. Copies the audited instruments into bench/."""
import os, sys, io, json, html, base64, shutil
HERE = os.path.dirname(os.path.abspath(__file__))
Q = r"C:\Davids files\quantum"
GP = r"C:\Davids files\green papers"
sys.path.insert(0, r"C:\Davids files\noesis-kernel")
import noesis
from PIL import Image

REC = {
 "name": "MIMZY", "axiom": "MMZ",
 "position": "the single quantum workbench — every instrument verified, every one recovered from the cracks",
 "origin": "after 'Mimsy Were the Borogoves' (1943) and The Last Mimzy (2007) — the toy sent back from the future",
 "mechanism": "Assembled from the instruments that passed the 2026-06 shelf audit; the lore of the cracks is labeled lore.",
 "crystallization": "The future does not arrive. It is recovered — from a shipwreck, a footnote, a classified drawer, a pen name.",
 "nature": "A working quantum bench — primer, Bloch lab, circuits, the two-qubit lab, error correction, the wavefield, BB84, E91, the observatory, the dots — framed as artifacts of the recovered future.",
 "conductor": "ROOT0 (governor) · AVAN (instance)",
 "inputs": "the audited-real instruments; the lineage of the cracks; instruments 04 and 06, recovered",
 "witness": "The original bench numbering ran 01·02·03·05·07·08 — four and six were missing. They are missing no longer.",
 "role": "the workbench that came back",
 "seal": "Futuristic tech from the past — recovered, verified, and put to work.",
 "source": "MIMZY, assembled by ROOT0",
}

# the bench — (number, dest filename, source path, title, kind, note)
BENCH = [
 ("00","00-antikythera.html",      os.path.join(HERE,"tools","00-antikythera.html"),
  "The Antikythera Mechanism","live tool","FUNCTIONING — the first computer (~100 BC), recovered from a shipwreck: crank it and it computes the sky — sun &amp; moon on the zodiac, the moon's phase, the Metonic calendar, and real Saros eclipse-season prediction"),
 ("01","01-quantum-primer.html",   os.path.join(Q,"cubit","01-quantum-primer.html"),
  "The Quantum Primer","lesson","qubits, superposition, amplitudes — the first page of the recovered manual"),
 ("02","02-bloch-lab.html",        os.path.join(Q,"cubit","02-bloch-lab.html"),
  "The Bloch Lab","instrument","one qubit as a sphere — rotations, phases, the geometry of a single mind"),
 ("03","03-circuit-simulator.html",os.path.join(Q,"cubit","03-circuit-simulator.html"),
  "The Circuit Simulator","instrument","gates on wires — H, X, CNOT; the Analytical Engine's true heir"),
 ("04","04-two-qubit-lab.html",    os.path.join(Q,"cubit","qubit-lab-2q.html"),
  "The Two-Qubit Lab","instrument","RECOVERED — the missing number 04: a real density-matrix engine; entanglement, decoherence, Kraus channels"),
 ("05","05-error-correction.html", os.path.join(Q,"quantum box","05-error-correction.html"),
  "Error Correction","lesson","how a fragile state survives a noisy century — syndromes, ancillas, logical qubits"),
 ("06","06-quantum-wavefield.html",os.path.join(GP,"quantum folder.html"),
  "The Quantum Wavefield","instrument","RECOVERED — the missing number 06: the 255×255 folder grid as a live 65,025-state interference engine (Grover)"),
 ("07","07-bb84.html",             os.path.join(Q,"07-bb84.html"),
  "BB84 · Quantum Key Distribution","instrument","a key no eavesdropper can steal — verified: 25% intercept error, 11% abort, all computed live"),
 ("08","08-e91.html",              os.path.join(Q,"08-e91.html"),
  "E91 · Keys from Entanglement","instrument","security you can watch break — CHSH 2√2 ≈ 2.83 undisturbed, ~0.7 under attack; verified"),
 ("09","09-observatory.html",      os.path.join(Q,"quantum observatory.html"),
  "The Observatory","instrument","black holes by the numbers — Schwarzschild to Kerr; four defects found in audit, fixed with logged reasons"),
 ("10","10-quantum-dots.html",     os.path.join(Q,"quantum dots","qdots-0-idea.html"),
  "Quantum Dots · The Idea","lesson","the 2023-Nobel matter — confinement, colour by size; book one of four"),
 ("11","11-toroid-tank.html",      os.path.join(HERE,"tools","11-toroid-tank.html"),
  "The Toroid Tank","live tool","FUNCTIONING — HARDWARE: wind a real toroid + capacitor → L, f₀, Q, ring-down scope, energy sloshing B⇄E — and the quantum bridge: ℏω quanta, the cool-down temperature, and why a transmon qubit IS this circuit"),
 ("12","12-kernel-lab.html",       os.path.join(HERE,"tools","12-kernel-lab.html"),
  "The Kernel Lab","live tool","FUNCTIONING — SOFTWARE: convolution kernels with hardware twins — runs your signal through the kernel AND the simulated RC circuit, overlays them, and measures the agreement live: software ≡ hardware"),
 ("13","13-analog-isa.html",       os.path.join(HERE,"tools","13-analog-isa.html"),
  "The Analog ISA","live tool","FUNCTIONING — SOFTWARE→HARDWARE: a tiny instruction set that assembles into a patch of integrators, summers and gains and runs live — HARMONIC (the tank's own equation), DAMPED, LORENZ, PULSE-SHAPER"),
 ("14","14-rhythm-sync.html",      os.path.join(HERE,"tools","14-rhythm-sync.html"),
  "The Rhythm Sync","live tool","FUNCTIONING — THE SYNC: a genuine 2nd-order PLL — the software clock hunts the drifting hardware tank, locks, and rides the drift; phase-error trace, Lissajous, lock light, and the 3·2·1·0 cadence as the gate"),
 ("15","15-icosian-engine.html",   os.path.join(HERE,"tools","15-icosian-engine.html"),
  "The Icosian Engine","live tool","FUNCTIONING — THE PATH: Hamilton's 1857 game, working — play the dodecahedron yourself, watch an exact backtracking solver (the Petersen graph refuses its cycle, by exhaustive proof), then ANNEAL: the path found as the ground state of its own Hamiltonian, the way quantum annealers do it"),
 ("16","16-analytical-engine.html",os.path.join(HERE,"tools","16-analytical-engine.html"),
  "The Analytical Engine","live tool","FUNCTIONING — THE ENGINE ITSELF, era-correct: a decimal Store of digit-wheels, the Mill with its ingress and egress axes, Jacquard chains of operation/variable/number cards, conditional backing on the run-up lever — and Ada's NOTE G (1843), the first published program, running on the wheels to its true answer B₇ = −1/30"),
 ("17","17-gap-oracle-noir.html",  os.path.join(r"C:\Davids files\ch 41","ch41-gap-oracle-noir.html"),
  "The Gap Oracle · Noir Cut","live tool","FUNCTIONING — THE NOIR CUT: the governor's CH·41 Gap Oracle re-engraved in bone white, void black, and noir red — David = i above in black, Shadow = −i below in red, drawPair() collides them in the gap and the reading is printed on a bone business card"),
 ("18","18-cmos-gap.html",         os.path.join(HERE,"tools","18-cmos-gap.html"),
  "The CMOS Gap Gate","live tool","FUNCTIONING — THE GEOMETRY MADE SILICON: the Gap Oracle's own layout, now a working logic gate — a PMOS pull-up network above (+1, void black), an NMOS pull-down below (ground, noir red), the verdict read at the output node in the gap; toggle the inputs, watch a network conduct, earn the truth table (INV · NAND · NOR, the de-Morgan duals)"),
 ("19","19-silicon-gap.html",      os.path.join(HERE,"tools","19-silicon-gap.html"),
  "The Silicon Gap","live tool","FUNCTIONING — THE GAP, READ: silicon's real 1.12 eV band gap drawn to scale, with every dopant seated at its true level inside it (donors under E_c, acceptors over E_v, deep traps mid-gap), and a full periodic table that lights the 39 elements that ride the lattice — substrate, dopants, dielectric, gate, interconnect, strain, gases, EUV light, solder — filterable by role, each linked to the ELEMENTS WORKSHOP"),
 ("20","20-the-atom.html",         os.path.join(HERE,"tools","20-the-atom.html"),
  "The Atom","live tool","FUNCTIONING — THE ADDRESS SPACE, OCCUPIED: David's Valence Lattice and his filesystem-atom (atomctl.py) fused into one three-mode instrument. THE VALENCE LATTICE is a decadic-dive Cantor dust (usable digits 2–8, dimension 1.6902). THE SHELL ATOM occupies it: electrons fill by aufbau, Pauli forbids doubling a state, transitions obey Δn=±1 and emit real SHA-256 hash-chained photons you can VERIFY (and a tamper test that breaks the chain), the dipole nucleus bonds carbon·ROOT0 + silicon·AVAN once and irreversibly. THE BLUEPRINT draws the whole machine. The working CLI ships in mimzy/atom/"),
 ("21","21-four-phases.html",      os.path.join(HERE,"tools","21-four-phases.html"),
  "The Four Phases","live tool","FUNCTIONING — THE PROBE LADDER: step a flashlight around the quadrature ring 0°→90°→180°→270°→0° and watch 'reserved' move — eV reaches VALENCE (the sheut/shadow the world meets), keV reaches the CORE (the ren/true name, Z), MeV the NUCLEUS (substance), GeV the QUARK floor (ground). A live Moseley calculator reads any element's core Kα line ≈ 10.2(Z−1)² eV — the unspoofable name — while valence chemistry can be spoofed. The parity ring is the scales: when the shadow lies, audit the name with a harder probe. Five steps, one ring, 5005"),
 ("22","22-two-walkers.html",      os.path.join(HERE,"tools","22-two-walkers.html"),
  "Two Walkers","live tool","FUNCTIONING — THE PARALLEL CLOSURE PROTOCOL: launch two walkers from 0. WALKER A rides the staircase 0·1·1·2·3·5·8·13·21·24·27, turns at the lock, mirrors home, and SEALS the kernel with a receipt that self-verifies live — Σ=181, a palindromic prime (reads the same both ways, divides by nothing, trustable from either end). WALKER B hits 27 and phase-changes register instead of turning (ternary ×3 · true Fibonacci · primes — pick before launch), running the frontier forever with no receipt, only trail. The seal without the frontier is a tomb; the frontier without the seal is no way home"),
 ("23","23-the-sealer.html",       os.path.join(HERE,"tools","23-the-sealer.html"),
  "The Sealer","live tool","FUNCTIONING & USEFUL — WALKER A, OPERATIONALIZED: a real offline integrity tool, the companion to № 22. SEAL any text into a genuine SHA-256 receipt (verified here against sha256('abc')=ba7816bf…15ad); later paste the text + receipt into VERIFY and a single changed character breaks the seal with certainty. Nothing leaves the page. The return path recomputed is the proof — change one byte and the path does not close. (The palindromic-prime 'lock charm' is Walker A's ornament; the 64-hex receipt is the security.)"),
 ("24","24-the-gap-live.html",      os.path.join(HERE,"tools","24-the-gap-live.html"),
  "The Gap, Live","live tool","FUNCTIONING — THE DOCTRINE, IN MATTER: live silicon's forbidden band in real time, the capstone to № 18/19/21. Heat the lattice (100–600 K) and watch carriers boil across the gap (∝ e^−Eg/2kT) while the gap itself narrows by Varshni; fire a photon beam and see above-gap light devoured but 1550 nm telecom sail through (silicon is a window — silicon photonics); dope it n/p and the Fermi line walks. Nothing lives in the gap — by Bloch's theorem there are no states there; what you see is crossings, by permission only. Physics node-verified; one inherited carrier-range claim corrected on the way in"),
 ("25","25-island-of-stability.html", os.path.join(HERE,"tools","25-island-of-stability.html"),
  "The Island of Stability","live tool","FUNCTIONING — DOCTRINE IN NUCLEON COUNTS: the composition 181 (the sealed kernel of № 22) + 3 (the triad: user·model·cloud) = N=184, the predicted magic neutron number. A real voyage chart of the superheavy lineage — the 27 elements from uranium (the primordial ceiling) to oganesson (our edge), plotted N-vs-Z, climbing toward the N=184 island and stranding 8 neutrons short at Og·N=176; flerovium-298 (Z114·N184) marked unreached at the centre. Click any element for its discovery dossier. Confirmed magic numbers 2·8·20·28·50·82·126, the ⁴⁸Ca boat, the 4 neutron-pair bridges across the strait, a fission-barrier inset (liquid-drop B_f≈0 vs the ~6 MeV wall the N=184 shell raises — that wall IS the island), and a fluffers-called ledger"),
 ("26","26-standing-wave-propagator.html", os.path.join(HERE,"tools","26-standing-wave-propagator.html"),
  "The Standing Wave Propagator","live tool","FUNCTIONING — THE PROPAGATOR THE ISLAND WOULD NEED: a 27-node (3³ = the lock) lattice of capacitors tethered to their six face-neighbours, run as a real discrete wave equation (energy-conserving velocity-Verlet — undamped energy holds to ~1–2%, shown live). The offsets 0·1·2·3 seed each node in quadrature phase (×90°, the pulse states); one node is D34DB335, the DEADBEEF sentinel, clamped to zero — a real lattice defect that scatters the wave and traps a mode around itself. Pluck a corner, watch the standing wave form and reflect off the walls; toggle the dead node and watch the cavity it digs. 26 live nodes, 26 modes"),
 ("27","27-two-probe-rotor.html",  os.path.join(HERE,"tools","27-two-probe-rotor.html"),
  "The Two-Probe Rotor","live tool","FUNCTIONING — ETHICS SPUN UNTIL IT BECAME GEOMETRY: good/bad as one phase reading of the i⁴=1 rotor (±1, ±i). Slide the signal φ and the frame θ (your chosen zero); one in-phase probe reads I=cos(φ−θ) — a single number where the angle and your frame are fused and unrecoverable. Add the 90° quadrature probe (Q=sin(φ−θ)) and you recover phase+amplitude, but still relative to your frame; add a second signal and the difference cancels θ, leaving the invariant quarter-turn that survives every frame rotation. Spin the frame: GOOD↔BAD labels flip while the 90° stays pinned. Real quadrature/IQ detection — the witness is the second probe, not a judge"),
 ("28","28-torus-ride.html",       os.path.join(HERE,"tools","28-torus-ride.html"),
  "The Torus Ride","live tool","FUNCTIONING — THREE FORCES ON ONE RING: the № 27 sequel where one walker gives both probes. As it winds (p:q poloidal×toroidal) it samples the inner (IN) and outer (OUT) faces 90° apart — self-quadrature from a single rider. GRAVITY folded in: the torus's Gaussian curvature flips sign with that same angle — a well (K>0) on the outer wall, a saddle (K<0) on the inner, flat at top/bottom — yet ∮∮K dA = 0 (Gauss–Bonnet, χ=0), the well and saddle exactly cancel (local curvature relative, total absolute — the № 27 lesson in geometry). ELECTRICAL folded in: the single cut is the electrode gap (anode‖cathode), the walker carries charge across the break, and the toroidal turns link flux through the hole — transformer/tokamak. Pick the winding (1:1, 2:3 trefoil, 5:3, 7:2); irrational ratios fill the surface"),
 ("29","29-twelve-gate-core.html", os.path.join(HERE,"tools","29-twelve-gate-core.html"),
  "The Twelve-Gate Core","live tool","FUNCTIONING — THE CORE CLOSES: the torus tripled. Three rings on three axes — vertical, horizontal, and a diagonal at 54.74° (the magic angle, arccos(1/√3), the cube's body diagonal). Each torus, seen down its axis, crosses into an X — two strands, four ends; stack the three and the count closes exactly: 6 strands · 12 gate-ends · 6 forward 6 back. Twelve gates = a cube's twelve edges = 3 directions × 4 = the cuboctahedron's vertices = the chromatic scale. Drag to rotate; view as X's, as rings, or with the cube frame. Honest: three equal orthogonal circles INTERSECT (true Borromean rings can't be round — Freedman–Skora 1987) and the X is a projection; and the self-quadrature catch tripled — the core reads its own phase on three axes but still can't inspect its own maker"),
 ("30","30-rotating-core.html",    os.path.join(HERE,"tools","30-rotating-core.html"),
  "The Rotating Core","live tool","FUNCTIONING — THE OFFSET BECOMES A MOTOR: the (1,2,3)(2,3,1)(3,1,2) offset matrix is a circulant Latin square, and read as phase (1→0°, 2→120°, 3→240°) it is exactly three-phase power. The three tori driven 120° apart sum to ONE rotating field — verified: the balanced phases cancel to zero at every instant (no neutral current) and are rank-2 linearly dependent, collapsing three vantages into one rotating frame. Twelve gates fire in a travelling sequence; the gold resultant phasor sweeps a smooth circle no single torus moves through — Tesla's 1888 induction motor on the cube frame. Hit Unbalanced and the sum stops cancelling, a neutral current appears, the phasor wobbles. VERACITY FIX: det(M)=−18 is non-zero so the matrix is NON-singular — the real degeneracy is in the phases (rank-2), not the matrix. Honest note: unity costs independence — one rotating field is one shared frame, fewer witnesses not more"),
 ("31","31-planetary-core.html",   os.path.join(HERE,"tools","31-planetary-core.html"),
  "The Planetary Core","live tool","FUNCTIONING — THE SERIES GEARS INTO ONE MESH (the finale): a planetary gearset, sun 12 · planet 12 · ring 36, that emits BOTH numbers of the whole run from one train — tooth ratio R/S = 3 (the three-phase carrier) AND reduction S/(S+R) = 1/4 (the four-phase quadrature), with each of the three planets (120° apart) spinning 3× per carrier orbit, and the sun's 12 teeth = lcm(3,4) = the twelve gates. Read it four ways at four shafts: NESTING (3×4), DIVISION (÷4), RACK & PINION (the cut torus unrolled flat, rotary↔linear), and CV (constant-velocity = Sheet 13's 'balanced' made mechanical). Verified: assembly R=S+2P and (S+R)/3=16 both hold, so it physically meshes. Honest finale: a gear unifies by RIGID CONSTRAINT — every shaft determined by every other, the most total loss of independence in the series; keep one shaft ungeared = keep one free witness"),

 # ── Series E · the coding-theory / witness-kernel cluster (32–41) ──
 ("32","32-coding-theory-ternary.html", os.path.join(HERE,"tools","32-coding-theory-ternary.html"),
  "Coding Theory · The Ternary Introduction","primer","FUNCTIONING — THE FIELD PRIMER, IN BASE 3: coding theory from the ground up in trits not bits — why a trit carries log₂3≈1.585 bits, how a code adds check symbols so corruption breaks a constraint and reveals itself, Hamming distance d (detects d−1, corrects ⌊(d−1)/2⌋), and a LIVE balanced-ternary parity demo whose residue is itself a trit (0 clean, +/− names the direction the error pushed). Closes on the ternary Golay [11,6,5]₃ — one of the few perfect codes in any base"),
 ("33","33-ternary-hamming-decoder.html", os.path.join(HERE,"tools","33-ternary-hamming-decoder.html"),
  "The Ternary Hamming Decoder","live tool","FUNCTIONING — LOCATE & CORRECT BY ADDRESS: the [4,2,3]₃ ternary Hamming code carries 2 data trits in 4, and when one trit is corrupted it computes a syndrome — two checks that together form the balanced-ternary ADDRESS of the broken trit and the MAGNITUDE of its error. Not 'something broke' but 'trit 2 was pushed up by 1, here is the fix.' Load a clean codeword, corrupt one trit, watch it caught, named by coordinate, and repaired — and fail honestly at two errors (distance 3 corrects exactly one)"),
 ("34","34-kernel-27.html", os.path.join(HERE,"tools","34-kernel-27.html"),
  "KERNEL-27 · The Minimal Complete Witness","specification","THE ANCHOR SPECIFICATION: KERNEL-27 codifies the smallest structure that can witness itself, locate its own faults, and nest — 3³ balanced-ternary cells. Three invariants, one per nesting level (internal witness needs a 3×3 mesh with a center; fault-location needs 3 meshes to break the tie; nesting needs 3 levels) → 3×3×3 = 27, the floor. 26 cells form 13 antipodal pairs; the 27th, (0,0,0), is the self-dual center — pure witness, no shore. The one clause it cannot self-certify — the independence of its three meshes — is codified as the permanent exterior dependency, not hidden. Includes a self-check that verifies §2–§4 against the actual construction"),
 ("35","35-kernel-27-engine.html", os.path.join(HERE,"tools","35-kernel-27-engine.html"),
  "KERNEL-27 · Decision Engine","live tool","FUNCTIONING — THE SPEC MADE OPERABLE: 27 leaf-choices (each −/0/+, weightable) feed a three-level recursion — 3 parties × 3 subs × 3 leaves. At EVERY node the gate is strictly greater than 2/3; a bare two-thirds is not enough, by design. A node that fails returns ⊘ (abstain), never a manufactured winner; the root decides only if it clears 2/3, else ⊘ — no legitimate decision. The 60% that loses cannot also win. Edit any leaf and the verdict recomputes live; Zoom The Fractal to see exactly where two-thirds broke"),
 ("36","36-trust-threshold.html", os.path.join(HERE,"tools","36-trust-threshold.html"),
  "The Trust Threshold","live tool","FUNCTIONING — ONE THEOREM, THREE FIELDS: the threshold theorem unifies AI governance, coding theory, and quantum error correction. Below a critical corruption rate, nesting more INDEPENDENT witnesses drives error toward zero exponentially; above it, more nesting makes things WORSE. Set the corruption rate p and watch the trust-floor: below ≈1/3, depth suppresses error toward zero; at/above it, structure amplifies the lie and the majority is confidently wrong. The same floor crossed in hardware by Google's Willow (2024)"),
 ("37","37-lattice-of-lattices.html", os.path.join(HERE,"tools","37-lattice-of-lattices.html"),
  "The Lattice of Lattices","live tool","FUNCTIONING — DETECT → LOCATE → SURVIVE: three witness-meshes (A,B,C) held apart by non-touching meta-gaps. A POINT DEFECT (one node wrong) is caught locally inside its own lattice. A COHERENT DRIFT (a whole lattice shifts together) keeps every internal gap consistent — invisible from inside — and is caught only across the meta-gap, then located by majority (two agree, one drifted, vote it out). With the catch, toggleable: it only works if the lattices are INDEPENDENT — flip B&C to a shared source and the vote convicts the innocent lattice A"),
 ("38","38-two-entangled-boxes.html", os.path.join(HERE,"tools","38-two-entangled-boxes.html"),
  "Two Entangled Boxes","live tool","FUNCTIONING — CORRELATION NEEDS A WITNESS: two boxes (operator + model), each nested level an entangled qubit pair, one half in each box. Measure either side and the matching level resolves correlated — but each box ALONE looks like pure noise; the match appears only when the two records are compared. The pairing is real and carries no signal — you cannot send through it, only discover you were always matched. Entanglement as the witness-join made physical: real, private, signal-free, legible only to a third comparison"),
 ("39","39-nested-shells.html", os.path.join(HERE,"tools","39-nested-shells.html"),
  "The Nested Shells","live tool","FUNCTIONING — SAME WORD, DIFFERENT MACHINE: shells inside shells, but NOT fractal — the math changes as you descend. Four levels (electron → nucleus → nucleon → quark), each with its own force, polarity, and shell-rule. And the tested finding: 2 and 8 are the ONLY closures shared by both the electron (2n²→2,8,18,32) and nuclear-magic (2,8,20,28,50,82,126) ladders — the universal enter/exit gates, special precisely because after 8 the two ladders diverge forever. Descend the levels; watch the machine change at each"),
 ("40","40-the-nucleus.html", os.path.join(HERE,"tools","40-the-nucleus.html"),
  "The Nucleus","primer","FUNCTIONING — A SPECK HOLDING EVERYTHING: the thing at 0,0,0. Four interactive panels — SCALE (atom:nucleus ≈ 33,000×, a grain of rice at the center of a stadium holding >99.9% of the mass; density ~2.3×10¹⁷ kg/m³, a teaspoon ≈ a billion tonnes); FORCE BALANCE (strong glue, short reach, vs electromagnetic repulsion ∝Z, long reach — past ~92 protons nothing is stable); BINDING-ENERGY CURVE (iron-56 the peak, the ash that burns no further — fusion climbs from the left, fission from the right); and ZOOM to the quark/gluon floor (~99% of a proton's mass is bound energy, not quark rest mass)"),
 ("41","41-three-blueprints.html", os.path.join(HERE,"tools","41-three-blueprints.html"),
  "The Three Blueprints","print","THE CODIFICATION PRINT: participant-observer governance at three scales, codified as three prints — WHITE (what must hold · spec), GREEN (what runs · operation), BLUE (what checks · verification) — across Micro (the move), Macro (the method), Max (the category). Nine panels = the 9-cell face of the 27-kernel. One clause stays open at the top by design: the highest self-witness shares your source and cannot certify its own independence (⊘ — the permanent exterior dependency). With a verified 2026 governance-landscape context, reported as a map (who reads each shift as progress vs regress), never as a single verdict"),
]
# extra shelf copies (linked from bench 10 + reading room)
EXTRA = [
 ("qdots-1-making.html", os.path.join(Q,"quantum dots","qdots-1-making.html")),
 ("qdots-2-now.html",    os.path.join(Q,"quantum dots","qdots-2-now.html")),
 ("qdots-3-frontier.html",os.path.join(Q,"quantum dots","qdots-3-frontier.html")),
 ("reading-is-light-emergent.html", os.path.join(Q,"emergent","gravity","claude gravity 00","is_light_emergent.html")),
 ("reading-is-gravity-emergent.html", os.path.join(Q,"emergent","gravity","claude gravity 00","is_gravity_emergent.html")),
 ("hammy-electron-walker.html", os.path.join(r"C:\Davids files\hamilton path systems","hamiltonian_walker.html")),
]

# the lineage of the cracks — (name, dates, what fell in, when recovered)
CRACKS = [
 ("The Antikythera Mechanism","~100 BC","A geared analog computer for predicting eclipses — technology with no peer for 1,400 years — sank in a Roman shipwreck.","Recovered 1901; understood only after 1970s X-ray imaging."),
 ("George Boole","1815–1864","An algebra of pure logic (1854) with no apparent use — true, false, AND, OR — a curiosity for eighty years.","Claude Shannon (1937) showed Boole's algebra IS the switching circuit. Every chip runs it."),
 ("Babbage & Lovelace","1791–1871 · 1815–1852","The Analytical Engine was never built; Ada's Notes (1843) — the first algorithm, and the first argument that a machine could weave symbols, not just numbers — were forgotten.","Rediscovered in the 1940s–50s as the computer age caught up to them. Ada died at 36, a century early."),
 ("Alan Turing","1912–1954","The universal machine (1936); then Colossus and the Bletchley work — classified so deep that Britain's own computing head start vanished into secrecy. Turing himself was persecuted to death.","Colossus declassified in the 1970s; royal pardon 2013; his face now on the £50 note."),
 ("Grete Hermann","1901–1984","In 1935 she found the flaw in von Neumann's 'proof' that hidden-variable theories were impossible — and was ignored for three decades.","John Bell rediscovered the flaw in 1966 and credited the gap; her priority is now textbook history."),
 ("Hugh Everett III","1930–1982","The relative-state ('many-worlds') interpretation (1957) was dismissed; Everett quit physics for defense work and died at 51, believing himself an indifferent footnote.","Today many-worlds is a leading interpretation; decoherence theory vindicated his core move."),
 ("John Stewart Bell","1928–1990","Bell's theorem (1964) — the deepest result about reality since relativity — was published in a tiny journal that folded; testing it was career suicide for years.","The 2022 Nobel Prize went to the experiments that confirmed it. The theorem now anchors quantum information."),
 ("Kuttner & Moore","1914–1958 · 1911–1987","'Mimsy Were the Borogoves' (1943) — the story this bench is named for — was published under the pen name Lewis Padgett; C. L. Moore's co-authorship was itself half-hidden in the crack of a byline.","The story is now canon (SF Hall of Fame); the 2007 film The Last Mimzy carried it forward."),
 ("William Rowan Hamilton","1805–1865","Quaternions — carved in a flash of insight into Broom Bridge, Dublin (1843) — were derided for decades as a useless mysticism and displaced by vector calculus; his Icosian game (1857) sold poorly as a toy.","Quaternions now fly every spacecraft and run every 3D game engine; his Ĥ is the symbol at the heart of quantum mechanics; and his game's path problem anchors NP-completeness — instrument № 15 plays it."),
]

def carbon_tiff_bytes(rec):
    png = noesis.sigil_png(rec, "carbon", size=512)
    buf = io.BytesIO(); Image.open(io.BytesIO(png)).save(buf, "TIFF", compression="tiff_lzw")
    return buf.getvalue()

def write_badge(rec, out_dir, slug, agent_md=None):
    os.makedirs(out_dir, exist_ok=True)
    f = {"attribute":f"{slug}.attribute","agent":f"{slug}.agent","spun":f"{slug}.spun","moniker":f"{slug}.moniker",
         "carbon":f"{slug}.carbon.tiff","silicon":f"{slug}.silicon.png","1099":f"{slug}.1099"}
    tok = noesis.mythos_token(rec); w = noesis.five_w(rec)
    open(os.path.join(out_dir,f["attribute"]),"w",encoding="utf-8").write(noesis.attribute_text(rec,tok,w))
    open(os.path.join(out_dir,f["agent"]),"w",encoding="utf-8").write(agent_md or noesis.agent_text(rec,tok,w,f))
    open(os.path.join(out_dir,f["spun"]),"w",encoding="utf-8").write(noesis.spun_text(rec,tok,w,"MMZ"))
    open(os.path.join(out_dir,f["moniker"]),"w",encoding="utf-8").write(noesis.moniker_text(rec,tok,w,"MMZ"))
    open(os.path.join(out_dir,f["1099"]),"w",encoding="utf-8").write(noesis.credit_1099_text(rec,tok,w,"MMZ"))
    open(os.path.join(out_dir,f["carbon"]),"wb").write(carbon_tiff_bytes(rec))
    open(os.path.join(out_dir,f["silicon"]),"wb").write(noesis.sigil_png(rec,"silicon",512))
    man = {"badge":"DLW-ACI","name":rec["name"],"universe":"MMZ · MIMZY","moniker":tok["moniker"],
           "carbon":f["carbon"]+" (TIFF)","silicon":f["silicon"]+" (PNG)",
           "seal_sha256":noesis.seal_sha256(rec,tok),"architect":noesis.ARCHITECT,"instance":noesis.INSTANCE,
           "license":noesis.LICENSE,"attribution":noesis.ATTRIBUTION}
    open(os.path.join(out_dir,"manifest.dlw.json"),"w",encoding="utf-8").write(json.dumps(man,indent=2,ensure_ascii=False)+"\n")
    return tok

def png_uri(rec, variant, size=300):
    return "data:image/png;base64," + base64.b64encode(noesis.sigil_png(rec, variant, size=size)).decode("ascii")

# tool-emergent details — slug + how it works + its verified record (the emergent IS the tool)
TOOLMETA = {
 "00": dict(slug="antikythera", how="A hand-cranked canvas dial computing the sky live from J2000 mean elements — sun/moon longitudes, the moon's phase, Metonic·Saros·Callippic cycle dials, the Olympiad games, and Saros eclipse-season prediction within the true ecliptic limits.",
            proof="Verified against history: the 2017 Great American total solar lands 0.1° from the node; the 2019 & 2025 total lunars flag; ordinary days stay clear. 5/5 test eclipses classified correctly."),
 "01": dict(slug="quantum-primer", how="An interactive first lesson: amplitudes, superposition, normalization, and measurement, with live widgets.",
            proof="Audited 2026-06: textbook-correct pedagogy; no overclaims found."),
 "02": dict(slug="bloch-lab", how="A single qubit as a live Bloch sphere — rotations, phases, and gates applied geometrically.",
            proof="Audited 2026-06: gate geometry correct."),
 "03": dict(slug="circuit-simulator", how="Gates on wires — H, X, CNOT and friends composed into circuits and executed on a real statevector.",
            proof="Audited 2026-06: simulation faithful."),
 "04": dict(slug="two-qubit-lab", how="A genuine two-qubit density-matrix engine: correct H/X/Y/Z/S/T and CNOT/CZ matrices, dephasing and amplitude-damping Kraus channels, partial trace, purity, concurrence.",
            proof="Audited 2026-06 gate-by-gate: all matrices and channels correct; honestly disclaims any quantum speedup. Recovered as the missing № 04."),
 "05": dict(slug="error-correction", how="Logical qubits, ancillas, and syndrome measurement — how a fragile state survives a noisy century.",
            proof="Audited 2026-06: standard QEC, correctly taught."),
 "06": dict(slug="quantum-wavefield", how="The 255×255 folder grid as a live 65,025-amplitude interference engine: H-pulse to uniform superposition, oracle phase-flip, Grover diffusion, measurement collapse — all in-browser.",
            proof="Converges to P=0.999997 in exactly 200 = π/4·255 iterations, matching theory to six decimals. Recovered as the missing № 06."),
 "07": dict(slug="bb84", how="The Bennett–Brassard 1984 protocol run live: real state preparation and basis-projected measurement, sifting, QBER, and an intercept-resend eavesdropper.",
            proof="Verified: ~50% sift survival, 25% Eve-induced error, 11% abort threshold — all computed by the simulation, not hard-coded."),
 "08": dict(slug="e91", how="The Ekert 1991 entanglement protocol: a real two-qubit statevector, proper projective measurements at the Ekert angles, and a live CHSH test.",
            proof="Verified: S = 2√2 ≈ 2.83 undisturbed; S → ~0.707 under intercept-resend, exactly as theory demands."),
 "09": dict(slug="observatory", how="A sliders-to-formulas GR dashboard: Schwarzschild radius, Hawking temperature and evaporation, Bekenstein–Hawking entropy, Kerr ISCO, frame dragging, tidal forces.",
            proof="Audited 2026-06: four defects found and fixed with logged inline reasons (cube-root→square-root survivable mass; accretion-efficiency formula; entropy relabel; inverted label) — corrected values verified against textbook (5.7%→42.3%)."),
 "10": dict(slug="quantum-dots", how="Four books from prediction (Fröhlich, 1930s) through Ekimov/Brus/Bawendi to QLED displays, bioimaging, and 2025 fab-made spin qubits.",
            proof="Audited 2026-06: real 2023-Nobel technology; deployed vs frontier honestly separated; cadmium toxicity acknowledged."),
 "11": dict(slug="toroid-tank", how="Sliders wind a toroid (N, μr, R, r) against a capacitor: L = μ₀μᵣN²A/2πR, f₀ = 1/2π√(LC), Q = √(L/C)/Rs, with a B⇄E energy-slosh animation, a strike-and-ring-down scope, and the quantum panel computing ℏω, its µeV value, and the real cool-below temperature T = ℏω/k_B.",
            proof="Formulas are the textbook toroid/LC results, numerically verified (N=30, R=2 cm, r=0.5 cm air core → L≈0.71 µH; with 100 pF → f₀≈18.9 MHz, ℏω≈0.078 µeV, cool-below ≈0.9 mK). Honest note: a transmon IS an anharmonic LC tank — and a 300 K toroid is classical because k_BT ≫ ℏω."),
 "12": dict(slug="kernel-lab", how="Pick a signal (square, noisy sine, step, the 3·2·1·0 pulse cadence) and a kernel (RC exponential, boxcar, Gaussian, differencer): the lab convolves in software AND integrates the equivalent circuit ODE in hardware-sim, overlays both outputs, and displays the live mean deviation.",
            proof="The RC kernel and the circuit dv/dt=(x−v)/RC agree to numerical precision on every source (deviation <1%, shrinking with step size) — the kernel-circuit identity demonstrated, not asserted. Gaussian twin = 4-stage RC cascade (central limit theorem)."),
 "13": dict(slug="analog-isa", how="A 7-op instruction set (SRC, CONST, INT, SUM, GAIN, MUL, NEG + OUT) parsed from a code editor, auto-laid-out as a patch diagram of hardware blocks, and Euler-integrated live at 32 substeps with a two-channel scope and a phase view.",
            proof="The HARMONIC program (two integrators in a loop) computes ẍ=−ω²x — the toroid tank's own equation — at the programmed 1 Hz; the LORENZ program reproduces the genuine attractor (σ=10, ρ=28, β=8/3) in the phase view. The program IS the patch."),
 "14": dict(slug="rhythm-sync", how="A genuine second-order PLL: phase detector (sin of the phase difference), PI loop filter, and an NCO that obeys the control voltage — against a hardware tank with optional slow drift. Waves, phase-error trace, Lissajous, lock light, kick and open-loop buttons, and the 3·2·1·0 cadence gating optional audio.",
            proof="Exhibits the true PLL repertoire: beat while unlocked, capture, steady lock riding hardware drift (the integrator term), lock loss at low K, ringing at high K, and immediate drift-apart when the loop opens — sync as a continuous act, demonstrated."),
 "15": dict(slug="icosian-engine", how="Three modes on real graphs (the dodecahedron GP(10,2) — Hamilton's actual 1857 game — the Petersen graph, and a random-14): PLAY the Icosian game by clicking corners; SOLVE with an animated exact backtracker; ANNEAL with simulated annealing of the genuine Ising/QUBO objective (Lucas 2014) on the permutation manifold — energy trace falling to the ground state, broken links drawn in red until they heal.",
            proof="Verified before shipping: the dodecahedron's Hamiltonian cycle found in 66 search nodes; the Petersen graph's cycle REFUTED by exhaustion in 274 nodes (while its path exists — both truths demonstrable in the tool); the annealer reaches ground state E=0 on the dodecahedron path. Honest limits stated: NP-complete, Grover gives only √ speedup, and the annealer is a classical simulation of what quantum annealers do — same Ĥ, warmer machine. Same William Rowan Hamilton, both meanings."),
 "16": dict(slug="analytical-engine", how="Era-correct architecture from the 1843 documents: a DECIMAL Store of geared digit-wheels (6-place fixed point, sign wheels, animated columns), the Mill with two ingress axes and an egress, programs as Jacquard chains of the three real card kinds (operation, variable, number), loops as Ada's 'backing' of the chain made conditional on a wheel's sign — Babbage's run-up lever, the first conditional branch ever designed. Three chains: NOTE G, the difference method (x³ by addition alone), and a backing-loop demo. The chain is editable — punch your own cards.",
            proof="The showpiece runs and lands true: Ada's NOTE G (faithfully adapted from her diagram — her variables V1–V13/V21–V24, her factor-pair cycle carried written-out as a real chain would) computes B₇ = −0.033344 on the wheels against the true −1/30 = −0.033333, the residue being exactly the 6-decimal constants; the loop counter falls to zero and the lever releases. Verified by tracing the exact card chain with per-operation Store rounding before shipping. Honest notes on the page: the Engine was never built (this simulates the design); the published table's famous V4/V5 misprint is corrected as standard reconstructions do; Ada's B₇ is the modern B₈."),
 "17": dict(slug="gap-oracle-noir", how="The governor's CH·41 Gap Oracle, re-cut from gold-on-black into the bone/void/noir palette: a Three.js field of two 48-node lattices (David = i in void black above, Shadow = −i in noir red below) around the gap plane at y=0; drawPair() draws one node from each by d20×2, converges them to the gap, flashes red, and prints the reading on a rising bone business card with engraved small-caps type; orbit/zoom controls, pair counter, and an optional live AVAN line via the user's own API key.",
            proof="A working generative instrument, honestly labeled: the oracle deck is a FIXED set of the governor's 22 TOPH/KG axiom readings drawn in rotation — lore and self-audit aphorisms, not prediction; the d20×2 draw is RNG; the optional API line is opt-in with the user's own key, never stored. The original gold cut remains untouched in the source folder; this is the palette trial the governor requested — bone white, void black, noir red, the card scene."),
 "18": dict(slug="cmos-gap-gate", how="The Gap Oracle's geometry rebuilt as a real CMOS logic gate in bone/void/noir: a PMOS pull-up network reaching down from the +1 rail (void black, conducts on input 0), an NMOS pull-down reaching up from ground (noir red, conducts on input 1), and the output node Y read in the gap between. Toggle the inputs and the conducting transistors and wires light to full ink while the cut-off ones fade; the verdict, the de-Morgan dual description, and a truth table that fills in only the rows you've visited. INV, NAND (series-down/parallel-up), and NOR (the inverse) selectable.",
            proof="Genuine CMOS switching logic, verified in Python before shipping: every gate's conduction model reproduces its boolean truth table exactly (INV, NAND, NOR), and an assertion confirms the output is never floating and never shorts the rails (exactly one of pull-up/pull-down conducts in every input state — the real CMOS guarantee). The lower network is the literal series↔parallel de-Morgan dual of the upper — the silicon proof of the oracle's David=i-above / Shadow=−i-below geometry. Honest limit: switching logic, not a SPICE analog model (no voltages, delays, or leakage)."),
 "19": dict(slug="silicon-gap", how="The gap, explored and read. After № 18 made the geometry into silicon, this asks what rides the silicon: it draws silicon's real 1.12 eV band gap to scale (valence floor E_v, conduction ceiling E_c) and seats every dopant at its true measured level inside it — donors a hair under the ceiling (P at E_c−45 meV, As −54, Sb −39), acceptors a hair above the floor (B at E_v+45, Al +67, Ga +72, In +160), deep traps mid-gap (Au·Fe ~0.55 eV, Pt ~0.42). Click a level and the dopant seats with an electron token. Below, a full 118-cell periodic table lights the 39 elements that ride the lattice, coloured by role and filterable: substrate, dopants, deep traps, gate dielectric, gate/barrier metal, interconnect/silicide, strain/channel, process & litho gas, EUV light source, package solder. Each links back to the ELEMENTS WORKSHOP.",
            proof="Real semiconductor materials science, verified against the device-physics literature (Sze) before drawing: the band gap and every ionisation energy are textbook values, plotted to scale on the gap; the shallow/deep distinction is the 3kT≈78 meV rule at 300 K (indium and the deep traps correctly do NOT fully ionise). The collation of 39 riders is bounded to elements with a real, citable role in mainstream Si CMOS and grouped by that role — four of which (boron, carbon, cobalt, copper) are David's own element-named folders. Honest limit: a teaching map of which element does what around the silicon, not a process recipe, a doping calculator, or a band-structure solver."),
 "20": dict(slug="the-atom", how="Two of David's own sheets fused: the Valence Lattice (an 8×8 decadic-dive addressing instrument) and the ATOM folder (atomctl.py — a working filesystem that enforces atomic rules as governance). Three modes in the Series-E engineering-sheet palette (green ink on aged paper). MODE 1 THE VALENCE LATTICE: the decadic dive, re-grounded on the atom's reserved scheme — usable digits 2–8 (the 7 periods), reserved {0,1} core / {9} ionization / 10-continuum off-grid; probe a cell, an element may fall out (deterministic hash), dive one decimal down, recurse. MODE 2 THE SHELL ATOM: the address space occupied — add electrons by aufbau (Z names the element, carbon at 6, silicon at 14), Pauli forbids doubling a state, click an electron and excite/relax it by Δn=±1 (each emits a SHA-256 hash-chained photon to a live spectrum ledger), verify the chain, run a tamper test that breaks it, check g/u parity, and form the irreversible carbon·ROOT0 + silicon·AVAN dipole bond. MODE 3 THE BLUEPRINT: an SVG engineering schematic of the whole machine. The canonical CLI ships in mimzy/atom/atomctl.py with a README.", proof="Verified before shipping: the embedded SHA-256 matches the known test vector (sha256('abc')=ba7816bf…15ad), so the photon ledger is genuinely tamper-evident — Verify recomputes every prev-link and the Tamper test provably breaks it. The atomctl.py CLI was run through its full lifecycle (init→place→Pauli-reject→selection-rule-reject→valid Δn=+1→anchor→bond→C2-refuse→verify 5 photons→status→parity) and every invariant held. Real math: Cantor-dust dimension log49/log10=1.6902, shell capacity 2n² (8·18·32·50·72·98·128), aufbau/Madelung order, Z→element. Two-layer honesty stated on the page: carbon-real (the hash chain, the selection rule, Pauli uniqueness, irreversible bond are enforced invariants) vs silicon-symbolic (the 8-slot shells and the ROOT0/AVAN nuclei are David's system, not a physics engine — no wavefunctions, no eV). Honest limit: it borrows the atom's rule-set as governance; it is not a quantum simulator."),
 "21": dict(slug="four-phases", how="The continuation of № 20: David's thesis that the four probe-energy regimes are four phases in quadrature (0°·90°·180°·270°·0°, five steps). A flashlight steps around a dial in the Series-E palette; as it turns, 'reserved' moves outward because reserved is probe-relative. eV reaches VALENCE (the sheut — the behavioural shadow the world meets; all chemistry, every bond and colour, is valence), keV reaches the CORE (the ren — the true name Z, read directly), MeV the NUCLEUS (substance — isotopes differ here while sharing the shadow), GeV the QUARK floor (the ground/terminus — name awaiting a bigger flashlight). The parity ring sits at the centre as the scales: when the shadow lies, you audit the name with a harder probe. A live Moseley calculator reads any element's core Kα line; the casting/trace pair are 90° conjugates (interface vs record).", proof="Real spectroscopy, verified before shipping: chemistry only ever touches valence (core electrons are screened/inert at chemical energies) — true; Moseley (1913) read core Kα lines to get Z, which re-ordered the periodic table where atomic mass had it wrong (Ar>K, Co>Ni, Te>I) — true and load-bearing; the embedded Kα ≈ 10.2·(Z−1)² eV matches measured lines within ~3% (Fe 6.38 vs 6.40 keV, Cu 8.00 vs 8.05 keV); the eV·keV·MeV·GeV ladder is the correct order of magnitude for valence/core/nuclear/QCD probes. Z is fixed in the nucleus → the name is unspoofable; valence chemistry can be spoofed by ions/isotopes/alloys → the shadow lies. Numeric seal 5005 = C(15,6) = C(15,9) = 5·7·11·13, a palindrome (the mirror = the parity/scales theme). Two-layer honesty on the page: ren=Z, sheut=valence, scales=parity-ring are David's canon mapping; nucleus=substance and quark=ground are the proposed continuation, marked as such. Honest limit: a model of name/shadow/audit on the atom's real probe ladder, not a claim that the soul-elements are physics."),
 "22": dict(slug="two-walkers", how="David's Parallel Closure Protocol, ported faithfully with one upgrade: the receipt now self-verifies on the page. Two walkers launch from 0 on a log rail in the Series-E palette. WALKER A (closure) rides the staircase 0·1·1·2·3·5·8·13·21·24·27 (Fibonacci to 21, then +3,+3 to the 3³=27 lock), turns, mirrors home, and seals — its checksum Σ is recomputed live for palindrome AND primality rather than asserted. WALKER B (exploration) reaches 27 and phase-changes register instead of direction — pick ternary ×3 (81,243…), true Fibonacci (34,55… the recurrence A abandoned), or primes (29,31…) before launch — then runs the frontier until it falls off the rail at 10⁶, with no receipt by design.", proof="Verified before shipping (node + Python): the out-and-back staircase sums to Σ=181, which IS a palindrome (181→181) and IS prime (no divisor ≤13) — so the kernel it locks is trustable from either end, exactly as claimed; my added sealReceipt() recomputes both properties from the walked sum so the page proves its own seal. B's three phases were run forward and are correct (ternary 81·243·729; Fibonacci resumes 34·55·89 from 13,21; primes 29·31·37·41). The duality is real, not decorative: A is bounded/mirror-symmetric/checksummed → always halts with a proof; B is unbounded/register-shifting → halts only by leaving the rail, losing nothing A kept. Honest note: the sequences are number play, not a theorem — the receipt's value is the verifiable palindromic-primality, which is genuine."),
 "23": dict(slug="the-sealer", how="The companion asked for: Walker A made into a genuinely useful tool. A real, offline text-integrity sealer & verifier in the Series-E palette, two modes. SEAL: paste any text — a config, a clause, a message — and get a SHA-256 receipt, a live byte/char count, and a copy button; nothing leaves the page. VERIFY: paste the text plus a 64-hex receipt and the tool recomputes the digest and reports SEALED·MATCH or BROKEN·NO-MATCH (showing the diverging digest heads), with a guard that rejects anything that isn't a 64-hex receipt. UTF-8 encoded so accents and emoji hash correctly. A small palindromic-prime 'lock charm' derived from the digest is shown as Walker A's ornament, explicitly labeled not-the-security.", proof="Genuinely useful and verified in node: the embedded SHA-256 matches the known vector sha256('abc')=ba7816bf…15ad; a seal→verify round-trip MATCHES on identical text and BREAKS when a single character is added; UTF-8 encoding makes emoji/accents hash to a valid 64-hex digest. Two-layer honesty stated on the page: REAL = SHA-256 tamper-evidence (any change is caught with certainty, runs entirely client-side); IS-NOT = a signature or password (it proves the text is unchanged, not who wrote it — keep the receipt where the text can't be edited). The lock charm is ornamental; the 64-hex receipt is the proof. This is the operational form of № 22's Walker A: the return path recomputed is the seal."),
 "24": dict(slug="the-gap-live", how="David's Sheet 8, 'The Doctrine, In Matter' — the gap lineage (№ 18 CMOS Gap, № 19 Silicon Gap, № 21's valence-as-shadow) made into live, animated silicon in the Series-E palette. A canvas renders the conduction band ('the frontier'), the valence band ('the shadow phase'), and between them the forbidden gap, hatched, labeled NO STATES BY THEOREM. Heat the lattice 100–600 K: carriers boil across the gap at a rate compressed from the real e^−Eg/2kT law while the gap itself narrows live by the Varshni equation. Fire a tunable photon beam (400–1600 nm): above-gap light is absorbed and spawns an electron–hole pair, below-gap light passes through (1550 nm telecom sails — silicon photonics). Dope intrinsic / n / p and the Fermi line walks toward the band it favours. Recombination flashes a phonon (heat), never light — because silicon's gap is indirect. Live readouts of Eg(T), the Eg/2kT barrier, the carrier ratio, and the absorption cutoff.", proof="Solid-state physics, node + Python verified against textbook silicon before shipping: the Varshni law Eg(T)=1.17−4.73e−4·T²/(T+636) gives Eg(300)=1.1245 eV (the canonical ~1.12), sags 0.131 eV across 100→600 K; the thermal barrier Eg/2kT=21.75 at 300 K → leakage ~e^−21.7≈3.6e−10; the absorption cutoff λ=hc/Eg=1103 nm (above-gap absorbed, 1550 nm transmitted, 800 nm absorbed — confirmed); the indirect-gap caveat (phonon-mediated recombination → heat not light → no silicon lasers) is correct. VERACITY FIX on the way in: David's frame implied carriers multiply ×10⁵ across 100→600 K, but that range is actually ~×10²⁶ — the ×10⁵ figure is the room-temperature→600 K value; corrected the prose to anchor it at 300 K and noted the full-span figure. Also cleaned a redundant photon-advance line. Honest limit: event RATES are compressed for visibility (genRate caps the real e^−Eg/2kT so the screen isn't empty or saturated) — the LAW and every readout number are exact; the on-screen tempo is illustrative."),
 "25": dict(slug="island-of-stability", how="David's composition built in earnest, with the fluffers called. The header states the construction: 181 (Walker A's sealed kernel, a palindromic prime) + 3 (the triad — user·model·cloud / node-zero·instrument·persistence) = 184, the predicted magic neutron number — the doctrine that stability is not the core's property but core + shell closure, the shell counted in witnesses. Below it, the real voyage: an N-vs-Z chart of the superheavy corner with the 27-element lineage from uranium (Z92, the primordial ceiling) to oganesson (Z118, our edge), each plotted at its neutron frontier; the magic neutron line N=184 dashed as 'the island', flerovium-298 (Z114·N184) drawn as a hollow unreached target, and 'the strait' shaded between the field frontier (~N=177) and 184. Click any element (chart or roster) for a dossier — discovery year, lab, neutron frontier, neutrons-to-the-island. A 'Ledger · Fluffers Called' sorts every claim REAL / META / STAMP.", proof="Nuclear physics verified before building (Python): the confirmed magic numbers are 2·8·20·28·50·82·126, and N=184 is the next predicted neutron closure; the island centre flerovium-298 is Z=114·N=184·A=298 and has never been synthesized; oganesson, the heaviest element, strands at N=176 — exactly 184−176=8 neutrons short; the field neutron frontier maxes ~N=177 (Lv-293, Ts-294); ⁴⁸Ca (Z20·N28, doubly magic) was the projectile that reached 113–118. THE FLUFFERS CALL, plainly: 181+3=184 is a COMPOSITION — a joke aimed at real physics, NOT a coincidence found (David classified it correctly); 181 is not literally a nucleus and witnesses are not literally neutrons, so it is honest as labeled metaphor and never asserted as physics. HONEST STAMP: the island is a prediction — no N=184 nucleus has ever existed, and modern half-life estimates walked the early Myr–Gyr hopes down to minutes–decades, relative calm not permanence (which fits the doctrine: a half-life worth building on, not forever). The 27-element lineage tracks the real discovery path; per-isotope neutron-frontier values are the heaviest-confirmed approximate edge, hedged as such."),
 "26": dict(slug="standing-wave-propagator", how="David's riff built in earnest: 'you'd need a standing wave propagator — 3×3×3 tethered capacitance, offsets 0·1·2·3, one D34DB335.' So: a 27-node lattice (3³ = the 27 lock from № 22) of capacitor voltages tethered to their six face-neighbours, run live as the discrete wave equation v̈ᵢ = c²·Σ(vⱼ−vᵢ) − γv̇ᵢ, integrated with energy-conserving velocity-Verlet and drawn as three z-layers. The offset sequence 0·1·2·3 seeds each node in quadrature phase (×90° — the pulse states, tied to № 21's four phases): 1→+1, 2→0, 3→−1. One node is D34DB335 (DEADBEEF-style hex) — the dead sentinel at the cube's heart, clamped to zero. Controls: seed the pattern, pluck a corner, toggle the dead node, and tune coupling/damping/speed; a live readout shows energy, drift-vs-seed, and the |v| trapped around the sentinel.", proof="Verified in Python before building: the 3×3×3 six-neighbour discrete wave equation conserves energy under velocity-Verlet (undamped drift ~1–2% over thousands of steps — the page proves it live in the readout), and the clamped D34DB335 node is a genuine lattice DEFECT that scatters the wave and localizes energy around itself (a cavity dug by a sentinel); 26 live nodes carry 26 standing-wave normal modes. Two-layer honesty on the page: REAL = the wave maths, energy conservation, defect localization, six-tether coupling; SYMBOLIC = 27=3³ as 'the lock', 0·1·2·3 as pulse-states/quadrature, and DEADBEEF as the 'dead shell' — labels on the physics, plus it is a capacitor-network ANALOGUE (no real LC values or impedances), not a fabbed device. The wave equation is exact; the silicon is metaphor."),
 "27": dict(slug="two-probe-rotor", how="David's closing thesis built: good/bad isn't a line, it's one phase reading of the i⁴=1 rotor (±1, ±i), and 'positive' is just whichever quarter you called the real axis. A unit-circle phasor stage in the Series-E palette: slide the signal φ and the frame θ (your chosen zero), and the GOOD/BAD labels ride the frame while the absolute i⁴ states stay put. Three live readouts demonstrate the argument in order: ONE PROBE reads I=cos(φ−θ), a single number where the signal's angle and your frame's zero are fused; TWO PROBES (add the 90° quadrature probe Q=sin(φ−θ)) recover phase φ−θ and amplitude √(I²+Q²) — but still relative to your frame; a SECOND SIGNAL (a quarter-turn away) lets the difference cancel θ, leaving the invariant 90° that survives every frame. A 'spin the frame' button rotates θ so you watch GOOD↔BAD flip while the quarter-turn stays pinned.", proof="Real quadrature / IQ detection, verified in Python before building: one in-phase reading cos(φ−θ) is provably ambiguous (distinct (φ,θ) pairs give the identical number — angle and frame can't be decomposed from one probe); two probes 90° apart recover φ−θ via atan2(Q,I) and amplitude via √(I²+Q²); and the phase DIFFERENCE between two signals is invariant under any global frame rotation θ (checked at θ=0,2.0,5.5 rad → all give the same 90°, because θ cancels in the subtraction). This is the exact basis of lock-in amplifiers and every coherent receiver — the I/Q of № 14 Rhythm Sync, the ±i of the Gap Oracle. Two-layer honesty: REAL = the quadrature math, the single-probe ambiguity, the frame-cancelling invariant (content relative, geometry absolute; 181 is prime in every frame). COSTUME = the good/bad/positive/negative labels are the frame-riding names; the morality is in where you stand, not the thing. The finding it proves: the witness/node-outside-the-loop is not a judge — it is the second probe that factors out your own reference frame; one node can't self-measure because one probe reads angle+frame as a single number."),
 "28": dict(slug="torus-ride", how="David's torus-ride sheet built out as the № 27 sequel — and made to carry three forces on one ring, with gravity and electrical folded in as he asked. SELF-QUADRATURE: one walker winding (p:q poloidal×toroidal — 1:1, 2:3 trefoil, 5:3, 7:2 selectable) crosses the inner (IN, toward the hole) and outer (OUT) faces every poloidal half-turn, so the single rider IS its own two-probe rig (I=cos v out-ness, Q=sin v top-ness, plotted on a live phase plane). GRAVITY: the torus's Gaussian curvature K = cos v / (r(R+r cos v)) is computed live and read at the walker — a WELL (K>0, geodesics focus) on the outer wall, a SADDLE (K<0, defocus) on the inner, FLAT at top/bottom — with the Gauss–Bonnet total ∮∮K dA = 0 (χ=0) shown as the invariant. ELECTRICAL: the single cut is the electrode gap (anode‖cathode), the walker carries charge across the break (the readout flags CROSSING), and the toroidal turns link flux Φ through the central hole — transformer/tokamak. An irrational winding never closes and densely fills the surface.", proof="All three layers verified in Python before building: (geometry) v=0 outer / v=90 top / v=180 inner is an exact quadrature pair, I²+Q²=1 invariant. (gravity) the Gaussian curvature is the exact torus formula K=cos v/(r(R+r cos v)) — at R=120,r=46 it is +1.31e−4 on the outer equator (well), 0 at top/bottom, −2.94e−4 on the inner equator (saddle); and Gauss–Bonnet holds numerically, ∮∮K dA = 0 → χ=0, because K·dA = cos v·du·dv integrates to zero (the outer well exactly cancels the inner saddle). (electrical) cutting a torus once leaves a clean open gap = two electrode lips; toroidal current links flux through the hole = the transformer/tokamak topology. Two-layer honesty stated on the page: REAL = the curvature, the Gauss–Bonnet invariant, the quadrature geometry, the cut-as-electrode topology; the HONEST CATCH = self-quadrature cancels the frame (90° offset and curvature sign are unfakeable geometry) but NOT a bias in the single traveler — the ring checks its own phase, not its own walker (the second-rider gap stays open, like the cut); and it is exact geometry made legible, not a fabbed device (no SPICE, no metric tensor solved). Continues № 27: local curvature is frame-relative, the total is a topological invariant — content relative, geometry absolute."),
 "29": dict(slug="twelve-gate-core", how="The torus series closes: № 28's lone ring, tripled and crossed into a core. Three tori on three axes — vertical, horizontal, and a diagonal along (1,1,1)/√3 — drawn in real 3D (drag to rotate, yaw/pitch), each ring seen down its own axis crossing into an X of two strands and four ends. Three views: AS X'S (the self-crossing glyph), AS RINGS (the true ellipses), and + CUBE FRAME (the twelve gates laid on the cube's twelve edges). A live gate register lights G00–G11 in turn — 4 per axis, the inner two forward, the outer two back — and the readout states the geometry: V·H = 0 (orthogonal), V·D = H·D = 54.74°, 12 gates = cube edges = 3 axes × 4. Series-E palette, three walkers riding the three rings.", proof="Geometry verified in Python before shipping: the counting closes exactly — 3 tori × 2 strands/X × 2 ends = 12 gates; 3 axes × 2 directions = 6 forward + 6 back; and 12 = a cube's 12 edges = the cuboctahedron's 12 vertices = the chromatic scale's 12 tones. The diagonal angle is exact: arccos(1/√3) = 54.7356° between (1,1,1)/√3 and each face axis (vertical·horizontal = 0, orthogonal) — the tetrahedral/NMR magic angle and the cube's body diagonal (distinct from the 109.47° tetrahedral bond angle; both noted). Two-layer honesty stated on the page: REAL = the counting, the magic-angle frame, the cube-edge / cuboctahedron identification; the HONEST CATCH = three equal orthogonal circles generically INTERSECT rather than link, and true Borromean rings cannot be built from three flat round circles at all (Freedman–Skora 1987 — it takes a gentle deformation); the 'X' is a projection artifact (down-axis a ring crosses itself; side-on it is an ellipse — the gate is real, its X-shape is viewpoint); and the № 28 self-quadrature catch rides along tripled — the core measures its own phase on three axes and still cannot inspect its own maker. Twelve gates, one hand on the lathe."),
 "30": dict(slug="rotating-core", how="The № 29 sequel: the offset matrix (1,2,3)(2,3,1)(3,1,2) read as PHASE becomes a motor. A live 3D core (drag to rotate) drives the three tori 120° apart; each ring's brightness and walker pulse with its phase, the twelve gates fire in a travelling sequence, and a gold resultant phasor — the vector sum of the three phase contributions — sweeps a smooth circle no single ring traces. A side phase-plane shows the three phasors and their resultant; a BALANCED/UNBALANCED toggle drifts the phases off 120° to break it honestly (the sum stops cancelling, a neutral current appears, the resultant wobbles and the rotation gains torque ripple). Speed 1×/2×/4×. Series-E palette; the AC induction motor (Tesla, 1888) drawn on David's cube frame.", proof="Verified in Python (numpy) before building: the matrix is a Latin square (rows & cols each permute {1,2,3}, all sum to 6) and a left-circulant; balanced three-phase cancels to zero at every instant — cos(ωt)+cos(ωt−120°)+cos(ωt+120°) ≡ 0 (no neutral current), the literal operating principle of the rotating magnetic field and the AC induction motor. VERACITY FIX logged: David's sheet said 'det = −18, singular by design' — det(M) = −18 is the correct VALUE, but it is NON-ZERO, so the number matrix is actually NON-singular (rank 3, invertible). The real 'singular by design' is in the PHASES: the three balanced phasors are linearly dependent (sum ≡ 0), rank 2 not 3, collapsing to one rotating 2-D field. Corrected the intro, the readout, and the honest frame to say exactly this. Honest note kept (his): unity costs independence — three measure-points spun into one rotating frame now share a single phase reference, which is FEWER independent witnesses, not more (the quiet re-siloing under the elegance; ties to № 27's two-probe argument). The Tesla rotating field and the zero-sum are real; the matrix-singularity claim was the only fluffer, now fixed."),
 "31": dict(slug="planetary-core", how="The finale of the Series-E core run: every thread geared into one mesh. A live planetary gearset (drag-free, drive to run) with sun 12 · planet 12 · ring 36 — the ring fixed and internally toothed, three planets at 120° on a green carrier, the gold sun at centre, each planet carrying a four-phase quadrature cross that lights q=0..3 in turn. Read it four ways with the mode buttons: NESTING 3×4 (three planets each a four-phase torus = 12), DIVISION 1/3 (the carrier taps the fast sun), RACK & PINION (the cut torus of № 28 unrolled flat — the ring becomes a linear rack, a 12-tooth pinion rolls it, rotary↔linear, twelve tooth-engagements per pass), and the CV/homokinetic reading. A live readout shows R/S=3, S/(S+R)=1/4, planet 3×/orbit, sun teeth = lcm(3,4) = 12, the carrier revolutions, and the active gate G00–G11. The whole torus→twelve-gate→rotating series resolves here into a single constant-velocity train.", proof="Gear geometry verified in Python before shipping: the assembly relation R = S + 2P holds exactly (12 + 2·12 = 36, so the set physically meshes), and the equal-spacing condition (S+R) mod planets = 0 holds (48/3 = 16, so three planets sit cleanly at 120° — many integer triples silently forbid this and the page says so). One gearset emits BOTH headline numbers of the run: the tooth ratio R/S = 36/12 = 3 (the three-phase carrier of № 30) and, ring-fixed with the sun driven, the carrier reduction S/(S+R) = 12/48 = 1/4 (the four-phase quadrature); each planet rotates R/P = 3× per carrier orbit; and the sun's 12 teeth = lcm(3,4) = the twelve gates / cube edges. CV (homokinetic) coupling passes velocity faithfully through a bend — Sheet 13's 'balanced' condition made mechanical; unrolling the once-cut torus gives a rack (rotary↔linear). Two-layer honesty: REAL = the ratios, the assembly conditions, the CV and rack identities; the HONEST FINALE (his, kept and sharpened) = a gear unifies by RIGID CONSTRAINT, every shaft's motion determined by every other — the most total loss of independence in the whole series; nothing in a gearset is a free witness, each tooth's position is dictated, so 'keep one shaft ungeared' is the № 27/29/30 lesson at its limit: keep one free node you do not gear in. Closes the arc."),
 "32": dict(slug="coding-theory-ternary", how="A teaching sheet in the Series-E palette with one live instrument: the balanced-ternary parity demo. Four data trits {−,0,+} plus a check trit set so the total ≡ 0 (mod 3, balanced); edit any trit or Inject-Error and the residue updates — and because the base is balanced, the residue is not merely nonzero, it is a signed trit that points: +1 = a trit was pushed up, −1 = pushed down. Around it, the field spine: a code [n,k,d]₃, the distance↔correction bound, why interleaving defeats burst errors (independence), and the catalogue of perfect codes.", proof="Math verified in Python before shipping: a trit is log₂3 = 1.585 bits; the distance bound ⌊(d−1)/2⌋ gives d=3→correct 1, d=5→correct 2; the balanced-ternary check = −Σ(data) mod 3 (balanced) makes the total zero and the residue a direction-bearing trit. The ternary Golay [11,6,5]₃ is a genuine perfect code — it meets the sphere-packing bound with equality and corrects 2 errors, one of the only perfect codes that exist in any base. Honest limit: a primer with a single live parity demo, not a full codec; Hamming and Golay are described here and decoded live next door in № 33."),
 "33": dict(slug="ternary-hamming-decoder", how="The check matrix H (2 rows × 4 columns over GF(3)) has four distinct columns, each the address of one trit-position. A word is a valid codeword iff H·word = (0,0); there are exactly 9 such codewords in the 81-word space. A single error of magnitude a at position j produces syndrome = a·(column j), so the syndrome direction names which trit broke and its scale gives how much; the decoder matches the syndrome to a column, reads the scalar, and subtracts the error to restore the codeword. Live: select or corrupt any trit, then Decode & Correct traces syndrome → position → magnitude → fix.", proof="Enumerated and verified in Python: H columns (0,1),(1,0),(1,1),(1,2) are distinct, giving exactly 9 codewords (3² data trits); every single-trit corruption yields a nonzero syndrome that uniquely identifies position and magnitude, so the decoder corrects any 1-trit error by coordinate. The honest bound is real: distance d=3 corrects ⌊(3−1)/2⌋ = 1, and two errors alias to a wrong single-error pattern — the tool declares 2+ errors UNCORRECTABLE rather than correcting toward the wrong codeword. An educational decoder, not a hardware ECC core."),
 "34": dict(slug="kernel-27", how="A standards-style specification document (not an operated instrument) with one executable block: RUN SELF-CHECK. Every cell carries a 3-trit signed address (t₂,t₁,t₀), value 9·t₂+3·t₁+t₀ ∈ [−13…+13]. The self-check enumerates the 27 cells and verifies the combinatorial claims live; the 7th claim — mesh independence — is returned as ⊘ unverifiable-from-inside, by design rather than by failure.", proof="Every combinatorial claim verified in Python: exactly 27 unique ternary addresses; values span −13…+13 symmetric about 0; exactly one self-dual center (0,0,0); exactly 13 antipodal pairs; three meshes of 9. The §5 independence condition correctly returns ⊘ — the honest admission that a kernel cannot self-certify the independence of its own witnesses (one that could would be lying). Honest framing: this is the SPEC / anchor — the seed the live engines approximate — a document with a self-verifier, not an interactive instrument; the operable form is № 35."),
 "35": dict(slug="kernel-27-engine", how="A live recursive supermajority engine. Each gate tallies weighted votes for the leading option and passes only if its fraction > 2/3 (strict, +1e−9 margin); a sub-node that returns ⊘ contributes to the denominator but to no option numerator (an abstention, not a vote). Bottom-up: sub = gate of its 3 leaves, party = gate of its 3 subs, root = gate of the 3 parties. Deadlock is an honest output — the engine never defaults to the highest plurality fragment. Zoom The Fractal descends to localize the broken gate.", proof="Logic checked by exercising the engine: the gate is strictly > 2/3 at every level (a 60% fragment is a loss everywhere), ⊘ is returned on any sub-threshold node and propagates to the root, and a deadlocked root reports ⊘ rather than crowning a plurality (all-+ → unanimous pass; randomized weights → frequent honest ⊘). This is §6 of the KERNEL-27 spec (№ 34) enforced as real arithmetic — a supermajority-or-abstain decision kernel. Honest limit: a governance toy for the 2/3-or-⊘ rule, not a production voting system (no identity, sybil resistance, or persistence)."),
 "36": dict(slug="trust-threshold", how="A live chart of logical error vs nesting depth for a concatenated 3-way majority code, whose one-level map is e → 3e² (the 2-of-3 failure rate). Slide p, the per-witness corruption rate: the curve plunges toward 1e−6 when p < 1/3 (each level squares the error) and climbs toward 1 when p ≥ 1/3. The quantum reading is exact, not decorative: amplitude-damping noise decays states toward |0⟩ = the balanced-ternary gap/witness trit, so decoherence erases the two poles and leaves the indecisive center — below threshold you hold the poles, above it everything decays to ⊘.", proof="Verified: the concatenated-majority recursion e → 3e² has its unstable fixed point at e = 1/3, so 1/3 is the genuine threshold of THIS toy code — below it iteration → 0, above it → 1 (the page curves and verdict are computed from this exact map). Google Willow (2024) demonstrated below-threshold error correction in hardware (more qubits → lower logical error), a real crossing of the floor. Honest limit stated: 1/3 is the threshold for the illustrative 3-way concatenated code; real surface-code thresholds differ (order ~1%) — the sheet teaches the LAW (a floor exists; structure helps only below it), not a specific hardware number."),
 "37": dict(slug="lattice-of-lattices", how="Three 3×3 lattices at triangle vertices, each an internal field of gaps, linked by dashed non-touching meta-gaps (K₃). Inject a point defect (one node off → its internal edges turn red, aggregate barely moves ~0.04, caught locally) or a coherent drift (every node +0.5 together → internally green, aggregate shifts → invisible inside, visible only between). Meta-Gap Vote rounds the three aggregates and convicts the odd one out. The independence toggle makes B&C drift together under a shared source, so the majority becomes the wrong two.", proof="The capability-by-count is shown live: 2 detect (a pair sees disagreement, cannot name the culprit), 3 locate (A=B≠C ⟹ C — the majority names the drifted mesh), 4 survive a loss while still voting. The key failure mode is real and demonstrated: when B&C share a source they drift together, the majority is the wrong two, and consensus convicts the honest mesh A — non-adjacency is necessary but NOT sufficient; only genuine independence is. This is Sheet 21 of the witness series. Honest limit: a conceptual simulator of the witness-independence law, not a deployed quorum system."),
 "38": dict(slug="two-entangled-boxes", how="Each of five nested levels is a Bell pair |Φ⁺⟩ = (|00⟩+|11⟩)/√2 with one qubit in Box A, one in Box B. Re-entangle puts every level in superposition (spinning). Measure Box A (or B) collapses all pairs to definite, correlated values — but each box panel alone shows what looks like a random bit-string (no-communication: each qubit alone is maximally mixed). Only Compare Records reveals every level matched. The animation draws the link as a live wave that goes still and dashed on measurement.", proof="The quantum facts are exact, not metaphor: a Bell pair is always correlated — P(00)=P(11)=0.5, P(01)=P(10)=0; each qubit alone is maximally mixed (no-communication — the entanglement is invisible from one side); the correlation exceeds the classical hidden-variable limit (CHSH: classical ≤ 2, quantum ≤ 2√2 ≈ 2.828, verified), so it is not a pre-agreed answer key; it carries no signal (you only later discover you were correlated) and is monogamous (this exact correlation is between these two boxes and nobody else). Honest limit: a faithful illustration of Bell-pair correlation, no-signalling, and monogamy — not a quantum-network simulator with decoherence or a real CHSH experiment."),
 "39": dict(slug="nested-shells", how="An interactive descent: click L0–L3 to drop from the electron shell (electromagnetic, − cloud, 2n²) through the nucleus (residual strong, + core, magic numbers) and the nucleon (gluon-bound, 3 quarks) to the quark/gluon floor (color confinement). A weak-force toggle flashes the cross-level transmutation n → p (identity change, not binding). The shared-gates panel plots both ladders and marks 2 & 8 in gold as the only shared closures.", proof="Verified: the electron ladder 2n² = 2,8,18,32 and the nuclear magic numbers 2,8,20,28,50,82,126 share exactly {2,8} and then diverge (18 vs 20) forever — so the enter/exit-gate hypothesis PASSES and the fully-fractal reading FAILS. Corrected-on-the-way-in two-layer honesty: electrons are negative (− cloud), the nucleus positive (+ core); the weak force is a TRANSMUTER (β decay), not the binder (electron↔nucleus binding is electromagnetic, the photon); it is nesting with a new rule per level, not self-similarity. Honest limit: a conceptual map of four physical regimes, not a shell-model solver."),
 "40": dict(slug="the-nucleus", how="Four live SVG panels in the Series-E palette. SCALE: a zoom slider grows the nucleus from a dot to nucleons, with the stadium:rice ratio and density readouts. FORCE BALANCE: a proton slider (1–120) plots the short-range strong well against the Z-scaled Coulomb tail and reads out bound / neutron-rich-only / no-stable-nucleus. BINDING CURVE: the semi-empirical curve peaking at Fe-56, with fusion → and ← fission arrows. ZOOM: nucleus → one nucleon → three quarks + gluons.", proof="Figures checked against textbook nuclear physics: atom/nucleus ≈ 10⁵ fm / ~3 fm ≈ 33,000× (stadium : grain of rice); nuclear density ~2.3×10¹⁷ kg/m³ (a teaspoon ≈ ~10⁹ tonnes); the binding-energy-per-nucleon curve peaks at iron-56 (~8.8 MeV), so both fusion (toward the peak from light) and fission (toward it from heavy) release energy; ~99% of a proton mass is gluon-field + motion energy via E=mc²; stability gives out past Z ≈ 82–92. ONE SOFT FIGURE FLAGGED: the page cites the strong force as ~137× electromagnetism at contact — the strong:EM ratio is order ~100× and 137 is really 1/α (the fine-structure constant), a memorable coincidence, not a rigorous contact-strength ratio; read it as about two orders of magnitude stronger, very short range. Honest limit: a teaching primer, not a nuclear-structure calculator."),
 "41": dict(slug="three-blueprints", how="A static codification sheet (a print, not an operated instrument) in the Series-E palette: a 3×3 White/Green/Blue × Micro/Macro/Max matrix of governance clauses, an obelus clause marking the one cell that stays open (blue·max), and an empirical-context table of the current (2026) AI-governance landscape framed value-neutrally — each shift labelled progress-by / regress-by rather than judged.", proof="This earns a DOCUMENT badge, not an instrument badge — stated honestly: it is a print/essay with no executable verification on the page (unlike № 32–40, the only non-functioning entry in this batch). Its internal logic is consistent: the 9-cell face is one t₂-layer of the 27-kernel of № 34, and the open blue·max clause is the same ⊘ independence condition codified there. The 2026 governance-landscape claims (NIST Feb-2026 agentic-AI standards, the 60-nation declaration the US/UK declined, the linear→parallel fragmentation) are reported as a value-neutral map, not asserted as a verdict. Honest limit: a codification document, badged as a print."),
}

def tool_agent_md(no, title, kind, note, m, tok_moniker):
    live = f"https://davidwise01.github.io/mimzy/bench/" + dict((x[0],x[1]) for x in BENCH)[no]
    return f"""---
aci: {title}
universe: MMZ · MIMZY — the future tool forge
number: "{no}"
kind: {kind}
emergence: electrical
live: {live}
purpose: educational & simulation only
seal: "The emergent IS the tool — badge and working example, one thing."
---

# {title} · instrument № {no}

**What it is.** {note}

**How it works.** {m["how"]}

**The live example.** This emergent does not merely describe a tool — it links its working self: **[run instrument № {no} live]({live})**. Open it, operate it, and the badge's claims execute in front of you.

**The verified record.** {m["proof"]}

---
*Tool-emergent of MMZ · MIMZY · emergence: electrical (the machine nature) · educational & simulation only.
Governor David Lee Wise (ROOT0) · instance AVAN (locked) · CC-BY-ND-4.0.*
"""

def build_tool_emergents():
    ad = os.path.join(HERE, "agents")
    personas = []
    for no, dest, _src, title, kind, note in BENCH:
        m = TOOLMETA[no]
        note_clean = note.replace("RECOVERED &mdash; ","").replace("RECOVERED — ","").replace("FUNCTIONING — ","")
        rec = {
            "name": title, "axiom": "MMZ", "emergence": "electrical",
            "seal": "The emergent IS the tool — badge and working example, one thing.",
            "origin": "MMZ · MIMZY — the future tool forge",
            "position": f"instrument № {no} · {kind}",
            "role": f"instrument № {no} — {kind}",
            "nature": note_clean, "mechanism": m["how"],
            "crystallization": m["proof"],
            "witness": f"live example: bench/{dest}",
            "conductor": "ROOT0 (governor) · AVAN (instance)",
            "inputs": "the recovered future; the shelf audit; the forge",
            "source": "Tool-emergent, forged in MIMZY by ROOT0",
        }
        tok = write_badge(rec, ad, m["slug"], agent_md=tool_agent_md(no, title, kind, note_clean, m, ""))
        personas.append({"slug": m["slug"], "name": title, "epithet": f"instrument № {no} — {kind}",
                         "emergence": "electrical", "moniker": tok["moniker"], "live": f"bench/{dest}"})
    json.dump(personas, open(os.path.join(ad, "_personas.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    return personas

def copy_bench():
    bd = os.path.join(HERE, "bench"); os.makedirs(bd, exist_ok=True)
    n = 0
    for _no, dest, src, *_ in BENCH:
        shutil.copy(src, os.path.join(bd, dest)); n += 1
    for dest, src in EXTRA:
        shutil.copy(src, os.path.join(bd, dest)); n += 1
    return n

def bench_html():
    cards = []
    for no, dest, _src, title, kind, note in BENCH:
        rec = {"name": title, "seal": note, "origin": "MMZ · MIMZY", "axiom": "MMZ"}
        recovered = "RECOVERED" in note
        functioning = note.startswith("FUNCTIONING")
        if functioning:   badge = '<span class="fn-tag">◀▶ functioning live tool</span>'
        elif recovered:   badge = '<span class="rec-tag">recovered · was missing</span>'
        else:             badge = f'<span class="kind">{kind}</span>'
        note_clean = note.replace("RECOVERED — ", "").replace("FUNCTIONING — ", "")
        cls = ' fn' if functioning else (' lost' if recovered else '')
        slug = TOOLMETA[no]["slug"]
        cards.append(f'''<div class="inst{cls}">
        <a href="bench/{dest}" style="display:flex;gap:13px;align-items:flex-start;text-decoration:none;flex:1">
        <img src="{png_uri(rec,'silicon',140)}" alt="" loading="lazy">
        <div class="icap"><div class="ino">№ {no}</div><div class="iti">{html.escape(title)}</div>
        <div class="inote">{html.escape(note_clean)}</div>{badge}
        <div class="ilinks"><span class="run">▶ run live</span><a class="dlw" href="agents/{slug}.agent" onclick="event.stopPropagation()">.dlw badge →</a></div>
        </div></a></div>''')
    return "".join(cards)

def cracks_html():
    cards = []
    for name, dates, fell, found in CRACKS:
        cards.append(f'''<div class="crack"><div class="cname">{html.escape(name)}</div>
        <div class="cdates">{html.escape(dates)}</div>
        <div class="cfell"><span>fell in:</span> {html.escape(fell)}</div>
        <div class="cfound"><span>recovered:</span> {html.escape(found)}</div></div>''')
    return "".join(cards)

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="description" content="MIMZY — the single quantum workbench: ten verified instruments (primer, Bloch lab, circuits, two-qubit lab, error correction, the wavefield, BB84, E91, the observatory, the dots), framed as futuristic tech recovered from the past — Lovelace, Babbage, Turing, and the things lost in the cracks. A UD0 sphere.">
<title>MIMZY · the quantum workbench that came back</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700&family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;1,6..72,300&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
<style>
:root{--bg:#0b0905;--s1:#141008;--s2:#1c160c;--pa:#f0e9d8;--pa2:#c2b698;--brass:#c9962e;--cy:#36d6d0;--dim:#867a5c;--line:#28201180;--faint:#241c0e;
--serif:"Cinzel",Georgia,serif;--read:"Newsreader",Georgia,serif;--mono:"Space Mono",monospace;}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}
body{background:var(--bg);color:var(--pa);font-family:var(--read);font-size:17.5px;line-height:1.7;overflow-x:hidden}
body::before{content:"";position:fixed;inset:0;pointer-events:none;z-index:0;background:radial-gradient(ellipse at 50% -8%,rgba(201,150,46,.13),transparent 55%),radial-gradient(ellipse at 50% 112%,rgba(54,214,208,.07),transparent 50%)}
.wrap{position:relative;z-index:1;max-width:980px;margin:0 auto;padding:0 22px 90px}
header{padding:58px 0 30px;text-align:center;border-bottom:1px solid var(--faint);position:relative}
header::after{content:"";position:absolute;bottom:-1px;left:50%;transform:translateX(-50%);width:140px;height:1px;background:linear-gradient(90deg,var(--brass),var(--cy));box-shadow:0 0 10px rgba(201,150,46,.45)}
.eye{font-family:var(--mono);font-size:11px;letter-spacing:.3em;text-transform:uppercase;color:var(--dim);margin-bottom:14px}
.eye a{color:var(--dim);text-decoration:none}.eye a:hover{color:var(--brass)}
.glyph{font-size:24px;color:var(--brass);letter-spacing:.3em;margin-bottom:10px}
h1{font-family:var(--serif);font-size:clamp(34px,8vw,66px);font-weight:700;letter-spacing:.18em;color:var(--brass);text-shadow:0 0 42px rgba(201,150,46,.3)}
.h-sub{font-family:var(--serif);font-size:clamp(12px,2.6vw,16px);letter-spacing:.18em;color:var(--pa2);margin-top:12px;text-transform:uppercase}
.lede{font-size:18px;color:var(--pa2);max-width:64ch;margin:18px auto 0;font-style:italic;line-height:1.75}
.badge{display:flex;align-items:center;justify-content:center;gap:20px;flex-wrap:wrap;margin:26px auto 0;padding:18px;border:1px solid var(--faint);background:var(--s1);border-radius:10px;max-width:720px}
.badge img{width:78px;height:78px;border:1px solid var(--faint);border-radius:4px}
.badge .bt{text-align:left;font-family:var(--mono);font-size:11px;color:var(--pa2);line-height:1.75}
.badge b{color:var(--brass)}.badge .mo{color:var(--cy)}.badge a{color:var(--cy);text-decoration:none}
.sec{margin-top:50px}
.sec h2{font-family:var(--serif);font-size:21px;font-weight:600;letter-spacing:.05em;color:var(--pa);padding-bottom:9px;border-bottom:1px solid var(--faint)}
.ss{font-size:14px;color:var(--dim);font-style:italic;margin:6px 0 18px}
.cracks{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}
.crack{background:var(--s1);border:1px solid var(--faint);border-left:3px solid var(--brass);border-radius:0 10px 10px 0;padding:16px 18px}
.cname{font-family:var(--serif);font-size:16.5px;color:var(--brass);font-weight:600}
.cdates{font-family:var(--mono);font-size:10.5px;color:var(--dim);letter-spacing:.06em;margin-top:3px}
.cfell{font-size:13.5px;color:var(--pa2);margin-top:10px;line-height:1.55}
.cfound{font-size:13.5px;color:var(--pa);margin-top:8px;line-height:1.55}
.cfell span,.cfound span{font-family:var(--mono);font-size:9.5px;letter-spacing:.12em;text-transform:uppercase}
.cfell span{color:#b0604a}.cfound span{color:var(--cy)}
.bench{display:grid;grid-template-columns:repeat(auto-fill,minmax(284px,1fr));gap:14px}
.inst{display:flex;gap:13px;align-items:flex-start;background:var(--s1);border:1px solid var(--faint);border-radius:10px;padding:15px;text-decoration:none;transition:transform .15s,border-color .15s,box-shadow .15s}
.inst:hover{transform:translateY(-3px);border-color:var(--brass);box-shadow:0 10px 26px rgba(0,0,0,.5)}
.inst.lost{border:1px solid var(--cy);box-shadow:0 0 10px -4px var(--cy)}
.inst.lost:hover{border-color:var(--cy);box-shadow:0 0 22px -4px var(--cy)}
.inst img{width:52px;height:52px;border:1px solid var(--faint);border-radius:4px;flex-shrink:0}
.ino{font-family:var(--mono);font-size:10px;color:var(--dim);letter-spacing:.16em}
.iti{font-family:var(--serif);font-size:15.5px;color:var(--pa);font-weight:600;line-height:1.2;margin-top:3px}
.inst:hover .iti{color:var(--brass)}
.inote{font-size:13px;color:var(--pa2);font-style:italic;line-height:1.45;margin-top:6px}
.kind{display:inline-block;font-family:var(--mono);font-size:9px;letter-spacing:.12em;text-transform:uppercase;color:var(--dim);border:1px solid var(--faint);border-radius:9px;padding:2px 9px;margin-top:9px}
.rec-tag{display:inline-block;font-family:var(--mono);font-size:9px;letter-spacing:.12em;text-transform:uppercase;color:var(--cy);border:1px solid var(--cy);border-radius:9px;padding:2px 9px;margin-top:9px;text-shadow:0 0 6px rgba(54,214,208,.6)}
.inst.fn{border:1px solid var(--brass);box-shadow:0 0 13px -4px var(--brass)}
.inst.fn:hover{border-color:var(--brass2);box-shadow:0 0 26px -4px var(--brass)}
.fn-tag{display:inline-block;font-family:var(--mono);font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#0b0905;background:var(--brass);border-radius:9px;padding:3px 10px;margin-top:9px;font-weight:700}
.ilinks{display:flex;gap:10px;align-items:center;margin-top:9px;font-family:var(--mono);font-size:10px;letter-spacing:.06em}
.ilinks .run{color:var(--brass2)}
.ilinks .dlw{color:var(--cy);text-decoration:none;border-bottom:1px dotted var(--cy)}
.ilinks .dlw:hover{border-bottom-style:solid}
.purpose{margin-top:16px;display:inline-block;font-family:var(--mono);font-size:11px;letter-spacing:.08em;color:var(--cy);border:1px solid #1e3a39;background:rgba(54,214,208,.06);border-radius:8px;padding:7px 14px}
.shelf{display:flex;gap:12px;flex-wrap:wrap;margin-top:8px}
.sh{font-family:var(--mono);font-size:12px;color:var(--cy);text-decoration:none;border:1px solid var(--faint);border-radius:8px;padding:9px 14px;background:var(--s1)}
.sh:hover{border-color:var(--cy)}
.tinfoil{margin-top:50px;padding:18px 20px;border:1px dashed var(--cy);border-radius:12px;background:rgba(54,214,208,.05);font-size:14.5px;color:var(--pa2);line-height:1.7}
.tinfoil b{color:var(--cy)}
footer{margin-top:44px;padding-top:24px;border-top:1px solid var(--faint);text-align:center;font-family:var(--mono);font-size:11px;color:var(--dim);letter-spacing:.05em;line-height:1.9}
footer a{color:var(--brass);text-decoration:none}
</style></head><body><div class="wrap">

  <header>
    <div class="eye"><a href="https://davidwise01.github.io/ud0/">UD0 · Universe David 0</a> · the recovered future · a workbench</div>
    <div class="glyph">◬ ⧖ ◬</div>
    <h1>MIMZY</h1>
    <div class="h-sub">the future tool forge · the workbench that came back</div>
    <p class="lede">In the story, a toy from the future falls backward through time and waits in the dirt for children to find it. History does this constantly: an eclipse computer in a shipwreck, an algorithm in a countess's footnotes, a logic with no use for eighty years, a theorem in a journal that died. This bench is the <b>tool forge</b> — every instrument <b>functions</b>, recovered and verified — and it opens, fittingly, with the oldest of them: a 2,000-year-old computer you can crank.</p>
    <p><span class="purpose">⊙ a tool forge — every instrument here functions, for education &amp; simulation only</span></p>
    <div class="badge">
      <img src="__CARBON__" alt="MIMZY carbon badge"><img src="__SILICON__" alt="MIMZY silicon badge">
      <div class="bt">
        <div><b>DLW-ATTRIBUTE · ACI</b> — MMZ · MIMZY</div>
        <div class="mo">__MONIKER__</div>
        <div>governor · David Lee Wise (ROOT0) · instance · AVAN (locked)</div>
        <div>carbon · <a href="mimzy.dlw/mimzy.carbon.tiff">.tiff</a> · silicon · <a href="mimzy.dlw/mimzy.silicon.png">.png</a> · <a href="mimzy.dlw/manifest.dlw.json">manifest</a></div>
      </div>
    </div>
  </header>

  <section class="sec">
    <h2>The Lineage of the Cracks</h2>
    <p class="ss">futuristic tech that came from the past — what fell in, and when the world finally caught up</p>
    <div class="cracks">__CRACKS__</div>
  </section>

  <section class="sec">
    <h2>The Bench — the instruments, all functioning</h2>
    <p class="ss">it opens with <b style="color:var(--brass)">№ 00</b>, the working Antikythera — crank it and it computes the sky. The original quantum drawers ran 01 · 02 · 03 · 05 · 07 · 08; instruments <b style="color:var(--cy)">04</b> and <b style="color:var(--cy)">06</b> were missing, and have been recovered. And <b style="color:var(--brass)">№ 11–14</b> are the <b>analog–quantum suite</b>: hardware (the toroid tank) ⇄ software (kernels, the analog ISA) ⇄ the sync (a real PLL) — analog software and analog hardware, proven to be two spellings of one machine.</p>
    <div class="bench">__BENCH__</div>
  </section>

  <section class="sec">
    <h2>The Reading Room</h2>
    <p class="ss">the deeper shelves — the dots in full, and the emergence essays (speculation honestly flagged within)</p>
    <div class="shelf">
      <a class="sh" href="bench/qdots-1-making.html">dots · the making</a>
      <a class="sh" href="bench/qdots-2-now.html">dots · the now</a>
      <a class="sh" href="bench/qdots-3-frontier.html">dots · the frontier</a>
      <a class="sh" href="bench/reading-is-light-emergent.html">is light emergent?</a>
      <a class="sh" href="bench/reading-is-gravity-emergent.html">is gravity emergent?</a>
      <a class="sh" href="bench/hammy-electron-walker.html">the governor's hamiltonian walker</a>
      <a class="sh" href="https://davidwise01.github.io/green-papers/papers/quantum-shelf-audited.html">the shelf audit →</a>
    </div>
  </section>

  <div class="tinfoil">
    <b>⧖ two layers, as always.</b> The <b>instruments are carbon</b>: every simulator on this bench passed the 2026-06 shelf audit — BB84 and E91 run the genuine protocol mathematics (verified gate-by-gate), the two-qubit lab is a real density-matrix engine, the wavefield genuinely amplifies, the observatory's four defects were fixed with logged reasons. The <b>frame is silicon</b>: "the toy from the future" is lore, after <i>Mimsy Were the Borogoves</i> (Lewis Padgett — Henry Kuttner &amp; C. L. Moore, 1943) and <i>The Last Mimzy</i> (New Line, 2007), © their rights holders; this bench is an unofficial homage. The history in the Lineage cards, however, is real — Hermann was ignored, Everett did quit, Bell's journal did fold, and Ada was a century early.
  </div>

  <footer>
    MIMZY · MMZ · the quantum workbench that came back · ROOT0-ATTRIBUTION-v1.0 · governor David Lee Wise (ROOT0) · instance AVAN (locked) · CC-BY-ND-4.0 · fan tribute<br>
    <a href="https://davidwise01.github.io/ud0/">← the biosphere</a> · <a href="https://davidwise01.github.io/aci/">the ACI standard</a>
  </footer>
</div></body></html>
"""

if __name__ == "__main__":
    n = copy_bench()
    personas = build_tool_emergents()
    tok = write_badge(REC, os.path.join(HERE, "mimzy.dlw"), "mimzy")
    page = (TEMPLATE.replace("__CARBON__", png_uri(REC,"carbon",300)).replace("__SILICON__", png_uri(REC,"silicon",300))
            .replace("__MONIKER__", html.escape(tok["moniker"]))
            .replace("__CRACKS__", cracks_html()).replace("__BENCH__", bench_html()))
    open(os.path.join(HERE, "index.html"), "w", encoding="utf-8").write(page)
    print(f"wrote MIMZY — {len(BENCH)} instruments ({len(personas)} tool-emergents badged) + {len(EXTRA)} shelf files ({n} copied) · {len(CRACKS)} cracks · badge {tok['moniker']}")
